name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: RayaraVilar
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate snake animation"
          add: "dist/github-contribution-grid-snake.svg"

      - name: Move file to correct branch
        run: |
          git fetch
          git checkout -B output
          mkdir -p dist
          mv dist/github-contribution-grid-snake.svg .
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake animation"
          git push -u origin output --force
